### ISSUE TITLE
Funkyness that I can't explain

### ISSUE THREAD

**Issue by stewartknapman** [luciddesign/orderly#5]
Hey @kelseyjudson 
I updated the element that this was being called on in bootstrapify and it's caused the thumbs to all jump about and have different heights set on the elements.

You can see here if you scroll down to featured products: http://bootstrapify-theme.myshopify.com/

I'll talk to you about it when your next in.

**Comment by kj** [comment]
I've made some fixes since, though not sure if they affect this. I think it's too late to test this now though so will close.
